### ISSUE TITLE
CSS help needed.

### ISSUE THREAD

**Issue by agnelvishal** [agnelvishal/Condense.press#1]
Could someone help in making the form look good by adding css? 
The form is in the index.html file.

**Comment by Calvinwuyts** [comment]
Hiya @agnelvishal , let's do this! I don't know exactly how you would want it, but I'll create an example or two and then you can comment on how you would want it changed :)

**Comment by dushivani** [comment]
I would like to work on this.

**Comment by Calvinwuyts** [comment]
@agnelvishal let me know what you think of this very initial CSS styling. Are there things you like or don't like? Would you like some colour in the form? Making a drawing of what you envision the form to be would help a lot to know what you have in mind. 

You can test out the new form in [this JSFiddle](https://jsfiddle.net/Calvinwuyts/w370g48u/)

**Comment by agnelvishal** [comment]
Thanks @Calvinwuyts The updated css can be seen at https://agnelvishal.github.io/Condense.press/ 
Maybe dotted lines for form border can be replaced with something else. 
Also the "display as" drop box looks smaller

**Comment by adsingh14** [comment]
Hi @agnelvishal !

Still need help ? Let me know. :)

**Comment by adsingh14** [comment]
@agnelvishal I would like you to check my PR. :slightly_smiling_face:

**Comment by agnelvishal** [comment]
Could someone suggest a better color combination?

**Comment by agnelvishal** [comment]
Thanks everyone. Now I have included php files of server
