### ISSUE TITLE
Another CSS help needed. #Hacktoberfest

### ISSUE THREAD

**Issue by agnelvishal** [agnelvishal/Condense.press#14]
When the card is hovered, some details are shown. It needs a better look. Could someone help?

**Comment by agnelvishal** [comment]
@adin234 @afro-code Feel free to ask any questions regarding setting up etc

**Comment by adin234** [comment]
created a PR with screenshot

**Comment by agnelvishal** [comment]
Thanks @adin234 Changes have been made and is live.

**Comment by agnelvishal** [comment]
Heading is required for chart and timeline. Can anyone help?

**Comment by adin234** [comment]
@agnelvishal why are the pull requests not being merged though? are you manually copying and pasting them?

**Comment by agnelvishal** [comment]
> @agnelvishal why are the pull requests not being merged though? are you manually copying and pasting them?

Sorry for the mistake. I have merged now
