### ISSUE TITLE
Alternate to iframes in php.

### ISSUE THREAD

**Issue by agnelvishal** [agnelvishal/Condense.press#16]
I have used iframes to display the data in the same page. But I don't think it is the right method. Maybe ajax? Maybe framework like vue.js? Can anyone guide me? #Hacktoberfest

**Comment by intelliapps** [comment]
I'm happy to have a go at replacing your iFrame with a div that is loaded by Ajax.

However, I would need to change db.php to return a html fragment (and rename it to articles.php). As that file has been rewritten by the 'Lumen Rest API' pull request that needs to be merged in before I can do it.

**Comment by agnelvishal** [comment]
Lumen Rest api has been merged :) 
@intelliapps
