### ISSUE TITLE
Api needed (rest or graphql)

### ISSUE THREAD

**Issue by agnelvishal** [agnelvishal/Condense.press#17]
Data is accessed from mysql database as seen in the file https://github.com/agnelvishal/Condense.press/blob/master/db.php Need help from someone, in converting into rest api or graphql api. #Hacktoberfest

**Comment by burrelle** [comment]
Do you want this API in something like Lumen or a framework like Laravel, or straight php?

**Comment by agnelvishal** [comment]
Would prefer Lumen

**Comment by burrelle** [comment]
I'll take this one then.

**Comment by burrelle** [comment]
#21
