### ISSUE TITLE
iframe dynamic size

### ISSUE THREAD

**Issue by agnelvishal** [agnelvishal/Condense.press#19]
The iframe which displays the data is not responsive. That is in mobile, it's width is high. What should I do?

**Comment by marcelorl** [comment]
Shadow dom would be a solution for this.
How about it?

**Comment by agnelvishal** [comment]
> Shadow dom would be a solution for this.
> How about it?
Could we use shadom doms for interacting with database in php?

**Comment by BKirev** [comment]
#20 there you go.
